"""Role column changed

Revision ID: 0aed0f0e8c51
Revises: 9af867283b49
Create Date: 2024-10-25 10:49:44.171582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aed0f0e8c51'
down_revision: Union[str, None] = '9af867283b49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'emp_role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'emp_role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
