"""Initial Migration

Revision ID: 9af867283b49
Revises: 
Create Date: 2024-10-25 10:41:58.691841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9af867283b49'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('emp_id', sa.Integer(), nullable=False),
    sa.Column('emp_name', sa.String(), nullable=False),
    sa.Column('emp_role', sa.String(), nullable=False),
    sa.Column('emp_salary', sa.Float(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('emp_id')
    )
    op.create_index(op.f('ix_employees_emp_id'), 'employees', ['emp_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_emp_id'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
